PWA101
ComPWA/compwa.github.io pull request #217
Opened 2023-11-20 17:39 UTC by shenvitor

2023-12-21 10:56 UTC, shenvitor commented
![model_petapi](https://github.com/ComPWA/compwa-org/assets/17490173/ec6bf191-bd5f-43b0-a6cb-da470b071630)

2024-03-13 19:21 UTC, shenvitor commented
Something wrong when doing github action workflow at the moment.
see [here](https://github.com/ComPWA/compwa.github.io/actions/runs/8270205354/job/22627218012?pr=217)

seems like a problem related to Sphinx Extension Error in configuration of environment variables of colours (?)

> 
> Extension error (sphinx_codeautolink.extension):
> Handler <bound method SphinxCodeAutoLink.create_references of <sphinx_codeautolink.extension.SphinxCodeAutoLink object at 0x707c6999eb60>> for event 'env-updated' threw an exception (exception: invalid literal for int() with base 10: 'yes')
> docnb: exit 2 (134.03 seconds) /home/runner/work/compwa.github.io/compwa.github.io> sphinx-build --color --keep-going -TW -b html docs/ docs/_build/html pid=3114
>   docnb: FAIL code 2 (135.22=setup[1.19]+cmd[134.03] seconds)
>   evaluation failed :( (135.98 seconds)
> Error: Process completed with exit code 2.

2024-03-13 22:47 UTC, shenvitor commented
Should I reopen this pull request?
Because the final words of the PWA101 documentation  is not yet finished 🤔

2024-03-14 17:14 UTC, shenvitor commented
> > Should I reopen this pull request?
> 
> Oops sorry 😅 Hadn't realized I typed a ['fix' keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)...

Seems like the problem is still here after the fix attempt..
Probably need to check which cell later...

2024-05-23 12:28 UTC, shenvitor commented
For the record, until this version: I have addressed most of @Smaldanerep1's comments.
Upcoming Next: @redeboer's turn 👀

2024-06-13 14:26 UTC, shenvitor commented
A few broken links were reported in link check:
https://github.com/ComPWA/compwa.github.io/actions/runs/9501304513/job/26186513533?pr=217#step:5:447
https://github.com/ComPWA/compwa.github.io/actions/runs/9501304513/job/26186513533?pr=217#step:5:451
https://github.com/ComPWA/compwa.github.io/actions/runs/9501304513/job/26186513533?pr=217#step:5:453
https://github.com/ComPWA/compwa.github.io/actions/runs/9501304513/job/26186513533?pr=217#step:5:737

2024-06-13 15:22 UTC, shenvitor commented
Wow 😱
according to: https://readthedocs.org/projects/compwa/builds/24685133/

Build #24685133
Pull Request #[217](https://github.com/ComPWA/compwa.github.io/pull/217) ([cbcd0d497ee7e99627154658c7dbedd1628f2e77](https://github.com/ComPWA/compwa.github.io/pull/217/commits/cbcd0d497ee7e99627154658c7dbedd1628f2e77))
Build failed
Error
The build was terminated due to time out. Read more about [time and memory limits in our documentation](https://docs.readthedocs.io/en/stable/builds.html#build-resources).

Maybe I should email them to apply: increase build limits on a per-project basis.
:)
![Screenshot 2024-06-13 at 17 21 58](https://github.com/ComPWA/compwa.github.io/assets/17490173/c5e7d9b1-aefa-45c5-b5f3-f797948674f9)

2024-06-14 14:01 UTC, redeboer commented
No need, we just need to keep CI time small with smaller notebooks

2024-06-20 09:15 UTC, redeboer requested changes
@shenvitor, I'm quite happy with the notebook, looks nice!
I've written more comments at https://compwa--217.org.readthedocs.build/report/999.html. Didn't finish, but once you have addressed them, I'll go over it myself and do some final polishing.

2024-07-03 11:59 UTC, shenvitor commented
https://github.com/ComPWA/compwa.github.io/actions/runs/9775660985/job/26986541402#step:5:865

for the record: link broken

2024-07-03 12:01 UTC, redeboer commented
Yeah Launchpad is broken, happens sometimes

2024-07-15 22:12 UTC, shenvitor commented on docs/report/033.ipynb
Interesting! So change to `jax.numpy` instead of `numpy` directly to increase computing speed (?)

2024-07-15 22:18 UTC, shenvitor commented on docs/report/033.ipynb
I see... the bunch size was the same as the size before. Now we changed the bunch size to be way larger than event size

2024-07-16 06:29 UTC, redeboer commented on docs/report/033.ipynb
I'm not sure yet, still slow

2024-07-16 06:29 UTC, redeboer commented on docs/report/033.ipynb
I'm not sure yet, still slow

2024-07-16 10:40 UTC, redeboer approved these changes
Ready to merge 🚙

2024-07-16 10:40 UTC, merged